language: objective-c
osx_image: xcode9.3

branches:
  only:
    - master
    # Tags formatted X.Y.Z*
    - /\d+\.\d+\.\d+.*/

env:
  global:
    - POD_LINT = "NO"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
    pod lib lint;
    fi

  - xcodebuild -workspace Zapic.xcworkspace -scheme Zapic archive | xcpretty
