language: objective-c
osx_image: xcode8.3
cache: cocoapods

branches:
  only:
    - master
    # Tags formatted vX.Y.Z*
    # - /v\d+\.\d+\.\d+.*/
    
#deploy: 
#  provider: releases
#  skip_cleanup: true
#  api_key: 
#    secure: $GITHUB_KEY 
#  file: Zapic.txt 
#  on: 
#    tags: true
#    repo: ZapicInc/Zapic-SDK-iOS
    
env:
  global:
  - POD_LINT = "NO"

script:
- set -o pipefail
- open -b com.apple.iphonesimulator
- xcodebuild -version
- xcodebuild -showsdks
- swiftlint

# Run `pod lib lint` if specified
- if [ $POD_LINT == "YES" ]; then
      pod lib lint;
  fi
    
##- xcodebuild -workspace Zapic.xcworkspace -scheme Zapic -destination 'OS=10.3.1,name=iPhone 7'  ENABLE_TESTABILITY=YES test | xcpretty
- xcodebuild -workspace Zapic.xcworkspace -scheme Zapic -destination 'OS=10.3.1,name=iPhone 7' build | xcpretty
